In [5]:
from __future__ import print_function
import numpy as np
from PIL import Image
import scipy.datasets

# Load the example image using scipy.datasets
lena = scipy.datasets.face()
# Create an array with four channels (RGBA)
data = np.zeros((lena.shape[0], lena.shape[1], 4), dtype=np.uint8)

# Assign RGB channels
data[:, :, :3] = lena
# Assign alpha channel
data[:, :, 3] = 255  # Set alpha to 255 (fully opaque)

# Create an image from the RGBA data
img = Image.fromarray(data, 'RGBA')

array_interface = img.__array_interface__
print("Keys", array_interface.keys())
print("Shape", array_interface['shape'])
print("Typestr", array_interface['typestr'])

numpy_array = np.asarray(img)
print("Shape", numpy_array.shape)
print("Data type", numpy_array.dtype)


Keys dict_keys(['version', 'data', 'shape', 'typestr'])
Shape (768, 1024, 4)
Typestr |u1
Shape (768, 1024, 4)
Data type uint8


In [ ]:
from __future__ import print_function
import requests
import re
import time
import numpy as np

# Function to fetch the stock price
def fetch_stock_price(symbol):
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={symbol}&interval=1min&apikey=YOUR_API_KEY'
    response = requests.get(url)
    data = response.json()
    last_refreshed = data['Meta Data']['3. Last Refreshed']
    price = float(data['Time Series (1min)'][last_refreshed]['4. close'])
    return price

# Replace 'YOUR_API_KEY' with your actual Alpha Vantage API key.
API_KEY = 'YOUR_API_KEY'
symbol = 'NVDA'

prices = np.array([])

for i in range(3):
    price = fetch_stock_price(symbol)
    prices = np.append(prices, price)
    avg = prices.mean()
    stddev = prices.std()

    devFactor = 1
    bottom = avg - devFactor * stddev
    top = avg + devFactor * stddev
    timestr = time.strftime("%H:%M:%S", time.localtime())

    print(timestr, "Average", avg, "-Std", bottom, "+Std", top)
    time.sleep(60)


In [10]:
import numpy as np
from PIL import Image
import scipy.datasets

# Load the Lena image from scipy.datasets
lena = scipy.datasets.face()

# Create an array with an additional alpha channel
data = np.zeros((lena.shape[0], lena.shape[1], 4), dtype=np.uint8)
data[:, :, :3] = lena
data[:, :, 3] = 255  # Set alpha channel to 255 (fully opaque)

# Create an image from the buffer
img = Image.fromarray(data, 'RGBA')
img.save('lena_frombuffer.png')

# Modify the image: set the alpha channel to Lena's grayscale values
data[:, :, 3] = np.mean(lena, axis=2).astype(np.uint8)  # Use the mean of RGB channels as the grayscale value
img = Image.fromarray(data, 'RGBA')
img.save('lena_modified.png')


In [14]:
import jpype
import numpy as np

# 1. Start the JVM
jpype.startJVM(jpype.getDefaultJVMPath())

# 2. Print hello world
jpype.java.lang.System.out.println("hello world")

# 3. Send a NumPy array
values = np.arange(7)
java_array = jpype.JArray(jpype.JDouble)(values.tolist())

for item in java_array:
    jpype.java.lang.System.out.println(item)

# 4. Shutdown the JVM
jpype.shutdownJVM()


JVMNotFoundException: No JVM shared library file (libjli.dylib) found. Try setting up the JAVA_HOME environment variable properly.

In [16]:
import numpy as np
import scipy.io

# Create a NumPy array
a = np.arange(7)

# Save the array to a MATLAB .mat file
scipy.io.savemat("a.mat", {"array": a})


In [18]:
import numpy as np

# Create a NumPy array
x = np.array([[1, 2], [3, 4]])

# Create a memoryview of the NumPy array
y = memoryview(x)

# Print memoryview properties
print("Format:", y.format)
print("Item size:", y.itemsize)
print("Number of dimensions:", y.ndim)
print("Readonly:", y.readonly)
print("Shape:", y.shape)
print("Strides:", y.strides)

# Convert memoryview back to a NumPy array
z = np.asarray(y)
print("Array from memoryview:\n", z)

# Modify the original array
x[0, 0] = 9
print("Modified original array:\n", x)
print("Array from memoryview after modification:\n", z)


Format: l
Item size: 8
Number of dimensions: 2
Readonly: False
Shape: (2, 2)
Strides: (16, 8)
Array from memoryview:
 [[1 2]
 [3 4]]
Modified original array:
 [[9 2]
 [3 4]]
Array from memoryview after modification:
 [[9 2]
 [3 4]]


In [20]:
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Activate the conversion of R objects to pandas DataFrame
pandas2ri.activate()

# Import the datasets package from R
datasets = importr('datasets')

# Fetch the 'mtcars' dataset from the 'datasets' package
mtcars = datasets.__rdata__.fetch('mtcars')['mtcars']

# Convert the R DataFrame to a pandas DataFrame
mtcars_df = pandas2ri.rpy2py(mtcars)

# Plot the 'wt' (weight) vs 'mpg' (miles per gallon)
plt.figure(figsize=(10, 6))
plt.title('R mtcars dataset')
plt.xlabel('wt')
plt.ylabel('mpg')
plt.scatter(mtcars_df['wt'], mtcars_df['mpg'], c='blue', marker='o')
plt.grid(True)
plt.show()


ModuleNotFoundError: No module named 'rpy2'