In [3]:
import urllib.request  # Use urllib.request in Python 3
import numpy as np
import re

response = urllib.request.urlopen('http://python.org/')
html = response.read().decode('utf-8')  # Decode bytes to string
html = re.sub(r'<.*?>', '', html)  # Remove HTML tags
carray = np.array(list(html)).view(np.chararray)  # Create a chararray from the string
carray = carray.expandtabs(1)  # Expand tabs to spaces
carray = carray.splitlines()  # Split into lines
print(carray)




[list(['']) list([' ']) list([' ']) ... list(['']) list(['']) list([''])]


In [7]:
from __future__ import print_function
import numpy as np

def double(a):
   return 2 * a

ufunc = np.frompyfunc(double, 1, 1)
print("Result", ufunc(np.arange(4)))


Result [0 2 4 6]


In [11]:
from __future__ import print_function
import numpy as np
from scipy.datasets import face
import matplotlib.pyplot as plt
import numpy.ma as ma

lena = face()
random_mask = np.random.randint(0, 2, size=lena.shape, dtype=bool)

plt.subplot(221)
plt.title("Original")
plt.imshow(lena)
plt.axis('off')

masked_array = np.ma.array(lena, mask=random_mask)
print(masked_array)

plt.subplot(222)
plt.title("Masked")
plt.imshow(masked_array)
plt.axis('off')

plt.subplot(223)
plt.title("Log")
plt.imshow(np.log1p(lena))  # Use np.log1p for numerical stability
plt.axis('off')

plt.subplot(224)
plt.title("Log Masked")
plt.imshow(np.log1p(masked_array))
plt.axis('off')

plt.show()


Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


[[[121 112 131]
  [138 129 --]
  [-- -- --]
  ...
  [119 126 74]
  [131 136 82]
  [-- 144 --]]

 [[-- -- --]
  [110 103 --]
  [130 -- 143]
  ...
  [-- 125 --]
  [134 141 87]
  [-- -- --]]

 [[-- -- 84]
  [-- 87 --]
  [115 -- --]
  ...
  [-- 126 --]
  [133 142 --]
  [144 -- 98]]

 ...

 [[87 -- 76]
  [-- 110 --]
  [107 -- 92]
  ...
  [120 158 --]
  [119 157 --]
  [119 -- --]]

 [[85 101 --]
  [95 -- 82]
  [112 127 96]
  ...
  [-- -- --]
  [-- 156 94]
  [120 156 --]]

 [[85 101 --]
  [97 -- 84]
  [111 126 --]
  ...
  [120 -- --]
  [119 -- 93]
  [118 154 92]]]


ValueError: arrays must be of dtype byte, short, float32 or float64

<Figure size 640x480 with 4 Axes>